<a href="https://colab.research.google.com/github/animeshdutta888/Upgrad/blob/master/Upgrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# !wget --header="Host: doc-0g-bk-docs.googleusercontent.com" --header="User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36" --header="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" --header="Accept-Language: en-US,en-IN;q=0.9,en;q=0.8" --header="Referer: https://drive.google.com/uc?id=1wpOtr264MFYrN1QVkpHug_jJ2Z8Eik85&export=download" --header="Cookie: AUTH_4bopc2hc8l34lnvure9p0f69o32upi3p_nonce=c6uhnue2s1nko; NID=162=dN9p5hojnjtNxQlJ9H2wVK1aumNobi8Aj0XWAhkg1hB7Er3vQZtHYlT86HCBYZfQHWz2bZi0FMmtHi_CP1aRF1PDB5BUzZSv-do9OFo2fvh04TdWdU78G3sj7dgsk3507V0Z6CJI9WxFGbvff9Db8ZV_NzjATAcjWKXMnQSlCUE" --header="Connection: keep-alive" "https://doc-0g-bk-docs.googleusercontent.com/docs/securesc/psusq0mr93vn4rl25l4i1rlqvv3toc55/dbkm7hhtpisdqqpcd6m4f63c823h601k/1553911200000/02500186615322573913/17243280734409231109/1wpOtr264MFYrN1QVkpHug_jJ2Z8Eik85?e=download&nonce=c6uhnue2s1nko&user=17243280734409231109&hash=bh3d9i0jjqu8hrhfch84konrpitqaj26" -O "train.zip" -c

In [580]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [0]:
train_df = pd.read_csv('/content/drive/My Drive/upgrad/bank-additional-full.csv',sep=';')
train_df = train_df.replace("unknown", np.NaN)


In [636]:
# drop rows with missing values
train_df.dropna(inplace=True)
# summarize the number of rows and columns in the dataset
print(train_df.shape)

(30488, 21)


In [637]:
train_df.corr()  #find co-relation and drop highly co-related columns

age  duration  campaign     pdays  previous  \
age             1.000000  0.007910 -0.002364 -0.050891  0.049231   
duration        0.007910  1.000000 -0.068406 -0.046239  0.018772   
campaign       -0.002364 -0.068406  1.000000  0.054312 -0.080766   
pdays          -0.050891 -0.046239  0.054312  1.000000 -0.590248   
previous        0.049231  0.018772 -0.080766 -0.590248  1.000000   
emp.var.rate   -0.050409 -0.023374  0.157739  0.268763 -0.403502   
cons.price.idx -0.035762  0.012768  0.127260  0.068010 -0.176775   
cons.conf.idx   0.125017 -0.009525 -0.011664 -0.102368 -0.027930   
euribor3m      -0.036481 -0.028922  0.140836  0.295188 -0.438863   
nr.employed    -0.064586 -0.040367  0.148069  0.370845 -0.488365   

                emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
age                -0.050409       -0.035762       0.125017  -0.036481   
duration           -0.023374        0.012768      -0.009525  -0.028922   
campaign            0.157739        0.127260      -0.011664   0.140836   
pdays               0.268763        0.068010      -0.102368   0.295188   
previous           -0.403502       -0.176775      -0.027930  -0.438863   
emp.var.rate        1.000000        0.766055       0.157593   0.969412   
cons.price.idx      0.766055        1.000000       0.027217   0.667292   
cons.conf.idx       0.157593        0.027217       1.000000   0.243637   
euribor3m           0.969412        0.667292       0.243637   1.000000   
nr.employed         0.900390        0.488871       0.075283   0.944871   

                nr.employed  
age               -0.064586  
duration          -0.040367  
campaign           0.148069  
pdays              0.370845  
previous          -0.488365  
emp.var.rate       0.900390  
cons.price.idx     0.488871  
cons.conf.idx      0.075283  
euribor3m          0.944871  
nr.employed        1.000000

In [0]:
train_df.drop(['euribor3m','nr.employed'],axis=1,inplace=True)

In [0]:
train_df.y=train_df.y.eq('yes').mul(1)


In [640]:
train_df.groupby(['y']).size()


y
0    26629
1     3859
dtype: int64

In [0]:
train_df["duration"] = train_df["duration"] / train_df["duration"].max()



In [0]:
X = pd.get_dummies(train_df, prefix_sep='_', drop_first=False)       #One-hot-encoding




In [0]:
from sklearn.model_selection import train_test_split

# We'll use this library to make the display pretty
from tabulate import tabulate

In [0]:
y = X.y
X = X.drop(["y"], axis=1)
list1=X.columns.values.tolist()
np.random.seed(seed=10)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=.30)


In [649]:
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=300)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
import pandas as pd
feature_imp = pd.Series(clf.feature_importances_,index=list1).sort_values(ascending=True)
feature_imp

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

default_yes                      7.382781e-09
default_no                       3.519499e-08
education_illiterate             1.779426e-04
month_dec                        1.244187e-03
job_housemaid                    3.103926e-03
education_basic.6y               3.989425e-03
month_nov                        4.019944e-03
job_unemployed                   4.024679e-03
month_jul                        4.101343e-03
job_entrepreneur                 4.130374e-03
month_aug                        4.259547e-03
job_student                      4.382174e-03
job_self-employed                4.447804e-03
month_sep                        4.492625e-03
month_apr                        4.981425e-03
month_jun                        5.507172e-03
education_basic.4y               5.893939e-03
job_retired                      6.226962e-03
job_services                     6.714466e-03
job_management                   7.436892e-03
contact_cellular                 7.504180e-03
month_mar                        7

In [650]:
from sklearn.preprocessing import StandardScaler
np.random.seed(seed=10)

sc = StandardScaler()  
X_train1 = sc.fit_transform(X_train)  
X_test1 = sc.transform(X_test)  

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  


In [651]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)  
y_train1=y_train
y_test1=y_test
X_train1 = lda.fit_transform(X_train1, y_train1)  
X_test1 = lda.transform(X_test1)  


/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [673]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
np.random.seed(seed=10)

classifier = RandomForestClassifier(max_depth=2,n_jobs=-1, n_estimators=100,class_weight={0:18,1:12})
classifier.fit(X_train1, y_train1)  
y_pred1 = classifier.predict(X_test1)


RandomForestClassifier(bootstrap=True, class_weight={0: 18, 1: 12},
            criterion='gini', max_depth=2, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=100, n_jobs=-1, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [675]:
cm = confusion_matrix(y_test1, y_pred1) 
print(cm)  
print('Accuracy:' + str(accuracy_score(y_test1, y_pred1)))  

[[7874  100]
 [ 907  266]]
Accuracy:0.889909259866623


In [676]:
from sklearn.metrics import roc_curve, auc
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test1, y_pred1)
roc_auc = auc(false_positive_rate, true_positive_rate)
roc_auc


0.6071141054975988

In [677]:
from treeinterpreter import treeinterpreter as ti
prediction, bias, contributions = ti.predict(classifier,X_test1)
print ("Prediction", prediction)
print ("Bias (trainset prior)", bias)
print ("Feature contributions:")
for c, feature in zip(contributions[0], list1):
    print(feature, c)


Prediction [[0.99255967 0.00744033]
 [0.92082259 0.07917741]
 [0.67005135 0.32994865]
 ...
 [0.99255967 0.00744033]
 [0.99255967 0.00744033]
 [0.85703399 0.14296601]]
Bias (trainset prior) [[0.91236466 0.08763534]
 [0.91236466 0.08763534]
 [0.91236466 0.08763534]
 ...
 [0.91236466 0.08763534]
 [0.91236466 0.08763534]
 [0.91236466 0.08763534]]
Feature contributions:
age [ 0.08019501 -0.08019501]


In [679]:
cm

array([[7874,  100],
       [ 907,  266]])

In [680]:
#Recall
print(round(7874 /(7874 + 100),2))


0.99


Recall - Specificity
TN / (TN + FP) [ MATRIX LINE 1 ]

For all NEGATIVE(0) REAL VALUES how much we predict correct ?

other way to understand, our real test set has 7874+100 clients that didin't subscribe(0), and our model predict 99% correct or 7874 correct and 100 incorrect

In [681]:
#Recall
print(round(266 / (266 + 907  ),2))



0.23


Recall - Sensitivity
TP / (TP + FN) [ MATRIX LINE 2 ]

For all POSITIVE(1) REAL VALUES how much we predict correct ?

other way to understand, our real test set has 266+907 clients that subscribe(1), and our model predict 23% correct or 266 correct and 907 incorrect, BUT REMEMBER, its best we miss by False negative instead of False Positive

In [682]:
#Precision
print(round(7874 / (7874 + 907),2))



0.9


Precision
TN / (TN + FN) [ MATRIX COLUMN 1 ]

For all NEGATIVE(0) PREDICTIONS by our model, how much we predict correct ?

other way to understand, our model pointed 7874 + 907  clients that didin't subscribe(0), and our model predict 90% correct or 7874 correct and 907 incorrect

In [683]:
#Precision
print(round(266 / (266 + 100),2))


0.73


TN / (TN + FN) [ MATRIX COLUMN 1 ]

For all POSITIVE(1) PREDICTIONS by our model, how much we predict correct ?

other way to understand, our model pointed 266+100 clients that subscribe(1), and our model predict 73% correct or 266 correct and 100 incorrect

In [684]:
F1_0 = 2*0.9*0.99/(0.9+0.99)
round(F1_0,2)

0.94

In [685]:
F1_1 = 2*0.73*0.23/(0.73+0.23)
round(F1_1,2)

0.35

In [686]:
AVG_precision =  (0.9*(7974/9147))+ (0.73*(1173/9147))
round(AVG_precision,2)

0.88

In [687]:
AVG_Recall =  (0.99*(7974/9147))+ (0.23*(1173/9147))
round(AVG_Recall,2)

0.89

In [688]:
AVG_f1 =  (0.945*(7974/9147))+ (0.48*(1173/9147))
round(AVG_f1,2)

0.89

In [689]:
cm

array([[7874,  100],
       [ 907,  266]])